<a href="https://colab.research.google.com/github/SureshNaid/python/blob/main/Day_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=sns.load_dataset('taxis')

In [5]:
df.tail(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6423,2019-03-12 08:10:47,2019-03-12 08:35:35,1,4.30,18.50,0.00,0.0,19.30,green,credit card,Saint Albans,Hillcrest/Pomonok,Queens,Queens
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.00,0.00,0.0,9.30,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.50,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.50,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.00,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [7]:
df['color'].isnull().sum()

0

In [9]:
df['payment'].isnull().sum()

44

In [11]:
(44/6433)*100

0.6839732628633608

In [10]:
df.isnull().sum()

pickup              0
dropoff             0
passengers          0
distance            0
fare                0
tip                 0
tolls               0
total               0
color               0
payment            44
pickup_zone        26
dropoff_zone       45
pickup_borough     26
dropoff_borough    45
dtype: int64

In [12]:
df.shape[0]

6433

In [13]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

In [ ]:
missing data handling
1) Imputation (fill in the blanks)
      1)stastical measures
      2)Parameter

2) delete data
      rows
      columns

In [21]:
df.drop('pickup_zone',axis=1)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Windsor Terrace,Brooklyn,Brooklyn

In [23]:
df.drop([2,3,6430,6432],axis=0,inplace=True)

In [26]:
a=np.random.randint(10,50,15)
a

array([32, 26, 38, 42, 19, 42, 34, 45, 39, 21, 28, 38, 33, 28, 13])

In [25]:
a[a>20]

array([38, 38, 37, 31, 47])

In [27]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [30]:
df['payment']=='cash'

0       False
1        True
2       False
3       False
4       False
        ...
6428    False
6429    False
6430     True
6431    False
6432    False
Name: payment, Length: 6433, dtype: bool

In [29]:
df[df['payment']=='cash']

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.0,0.0,9.3,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.8,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.0,0.0,13.8,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.0,0.0,14.8,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.8,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6420,2019-03-16 15:39:23,2019-03-16 15:46:18,2,1.20,7.0,0.0,0.0,7.8,green,cash,Central Harlem,Upper West Side North,Manhattan,Manhattan
6422,2019-03-22 20:17:35,2019-03-22 20:36:07,1,4.02,16.0,0.0,0.0,17.3,green,cash,Washington Heights South,Spuyten Duyvil/Kingsbridge,Manhattan,Bronx
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.0,0.0,0.0,9.3,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.0,0.0,20.0,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.0,0.0,17.3,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn

In [31]:
df[(df['payment']=='cash') & (df['total']>15)]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.0,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.5,0.0,0.0,16.80,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
16,2019-03-15 12:36:05,2019-03-15 12:54:28,1,2.12,13.0,0.0,0.0,16.30,yellow,cash,East Chelsea,Meatpacking/West Village West,Manhattan,Manhattan
26,2019-03-03 02:45:36,2019-03-03 03:02:14,1,3.35,13.5,0.0,0.0,17.30,yellow,cash,West Chelsea/Hudson Yards,Seaport,Manhattan,Manhattan
29,2019-03-06 08:09:03,2019-03-06 08:27:11,1,0.92,12.0,0.0,0.0,15.30,yellow,cash,UN/Turtle Bay South,Garment District,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6407,2019-03-07 16:35:42,2019-03-07 16:50:03,1,2.68,12.0,0.0,0.0,16.55,green,cash,Morningside Heights,Upper East Side North,Manhattan,Manhattan
6408,2019-03-04 07:27:58,2019-03-04 07:49:25,1,6.48,22.0,0.0,0.0,25.55,green,cash,East Harlem North,Clinton East,Manhattan,Manhattan
6422,2019-03-22 20:17:35,2019-03-22 20:36:07,1,4.02,16.0,0.0,0.0,17.30,green,cash,Washington Heights South,Spuyten Duyvil/Kingsbridge,Manhattan,Bronx
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.0,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.0,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn